# Contains various test cases for the whole system

version: '2'

networks:
  autodeploy:

services:
  interactive:
    build: .
    networks:
      - autodeploy
    volumes:
      - ".:/home/autodeploy"
    depends_on:
      - database
    command: bash

    #   specs_and_deploy_pass:
    #     build:
    #       dockerfile: ./Dockerfile
    #       context: .
    #       args:
    #         mockbundle: mock_bundle.rb
    #     volumes:
    #       - ".:/home/autodeploy"
    #     networks:
    #       - autodeploy
    #     depends_on:
    #       - database
    # 
    #   specs_fail:
    #     build:
    #       dockerfile: ./Dockerfile
    #       context: .
    #       args:
    #         mockbundle: mock_bundle_specs_fail.rb
    #     volumes:
    #       - ".:/home/autodeploy"
    #     networks:
    #       - autodeploy
    #     depends_on:
    #       - database
    # 
    #   deploy_fails:
    #     build:
    #       dockerfile: ./Dockerfile
    #       context: .
    #       args:
    #         mockbundle: mock_bundle_deploy_fail.rb
    #     volumes:
    #       - ".:/home/autodeploy"
    #     networks:
    #       - autodeploy
    #     depends_on:
    #       - database

  database:
    image: "mysql:5.5"
    networks:
      - autodeploy
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=pw4root
