# Contains various test cases for the whole system

version: '2'

networks:
  autodeploy:

services:
  interactive:
    build: .
    networks:
      - autodeploy
    volumes:
      - ".:/home/autodeploy"
    depends_on:
      - database
    command: bash

  database:
    image: "mysql:5.5"
    networks:
      - autodeploy
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=pw4root
