# Contains various test cases for the whole system

version: '2'

networks:
  autodeploy:

volumes:
  bundler:

services:
  test:
    build: .
    networks:
      - autodeploy
    volumes:
      - ".:/home/autodeploy"
      - "bundler:/usr/local/bundle"
    depends_on:
      - database

  test_deploy_fail:
    build: .
    environment:
      - TEST_DEPLOY_FAIL=true
    networks:
      - autodeploy
    volumes:
      - ".:/home/autodeploy"
      - "bundler:/usr/local/bundle"
    depends_on:
      - database

  inspect:
    build: .
    networks:
      - autodeploy
    volumes:
      - ".:/home/autodeploy"
      - "bundler:/usr/local/bundle"
    depends_on:
      - database
    entrypoint: /bin/bash /home/autodeploy/test_environment/show_last_run.bash

  database:
    image: "mysql:5.5"
    networks:
      - autodeploy
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=pw4root
